spring:
  application:
    name: Praktyki
  datasource:
    url: jdbc:postgresql://localhost:5432/praktyki
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:changelog-master.xml